export enum SizeEnum {
  SIZE_0 = '0',
  SIZE_2 = '2',
  SIZE_4 = '4',
  SIZE_6 = '6',
  SIZE_8 = '8',
  SIZE_10 = '10',
  SIZE_12 = '12',
  SIZE_14 = '14',
  SIZE_16 = '16',
  SIZE_DIVIDER_1 = 'SIZE_DIVIDER_1',
  XXS = 'XXS',
  XS = 'XS',
  S = 'S',
  XS_S = 'XS/S',
  M = 'M',
  L = 'L',
  M_L = 'M/L',
  XL = 'XL',
  XXL = 'XXL',
  XL_XXL = 'XL/XXL',
  SIZE_DIVIDER_2 = 'SIZE_DIVIDER_2',
  ONE_SIZE = 'ONE SIZE'
}